author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2024-02-12
description = Optimal bandwidth for kernel density estimation
tags = C14
min-version = 2022a
public = kde_bandwidth
help = KdeBandwidth_help.md
sample-script = KdeBandwidth_sample.inp
data-requirement = no-data-ok
